name: khb test

on:
  push:

env:
  # set a default terminal for various cmds that expect it
  TERM: xterm
  # COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
  # slack_url: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  run-CI-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          ## - macos-latest
        value: [true]
    env:
      debug: ${{ matrix.value }}
      SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW: ${{ secrets.SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW }}
      TMATE_AUTHORIZED_KEYS_URL: ${{ secrets.TMATE_AUTHORIZED_KEYS_URL }}
    steps:
      # be sure to create release.tar in default path
      - run: |
          echo test
          echo ::set-env name=RELEASE_TAG::"${GITHUB_REF#refs/heads/}"
      - uses: PMET-public/github-release@master
        with:
          tag: ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          files: release.tar
          draft: false
          gzip: false
          prerelease: true
      - name: keep alive to debug
        if: ${{ failure() }}
        uses: PMET-public/action-tmate@master
